apiVersion: v1
kind: Service
metadata:
  name: technician-server-service
  labels:
    app: technician-server
    component: backend
    service: technician
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP
  selector:
    app: technician-server
