apiVersion: v1
kind: Service
metadata:
  name: appointment-server-service
  labels:
    app: appointment-server
    component: backend
    service: appointment
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
  selector:
    app: appointment-server
