apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: customer-server-ingress
spec:
  rules:
    - host: customer.your-domain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customer-server-service
                port:
                  number: 8001
